name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_core: ^3.1.1
  fluttertoast: ^8.2.5
  provider: ^6.0.1
  shared_preferences: ^2.1.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^1.2.1

  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  firebase_auth: ^5.1.1

  cupertino_icons: ^1.0.8
  flutter_config: ^2.0.2
  flutter_dotenv: ^5.1.0
  intl: any

dev_dependencies:
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

