// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmEiJAaFOoibsIzX2JR-f90C12Jz09yY',
    appId: '1:883212268237:web:373d7173a751eedc64ef84',
    messagingSenderId: '883212268237',
    projectId: 'userservice-423506',
    authDomain: 'userservice-423506.firebaseapp.com',
    storageBucket: 'userservice-423506.appspot.com',
    measurementId: 'G-JP1BL1GDZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNl1-7aITTiD7PRbcTbwXjSM0AR7hZFfk',
    appId: '1:883212268237:android:2c46fe158d80424264ef84',
    messagingSenderId: '883212268237',
    projectId: 'userservice-423506',
    storageBucket: 'userservice-423506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxKxlyZN-HoZA5JIeh1gFOBUdc0qonwM',
    appId: '1:883212268237:ios:0dfc2a05c3e89cc864ef84',
    messagingSenderId: '883212268237',
    projectId: 'userservice-423506',
    storageBucket: 'userservice-423506.appspot.com',
    iosBundleId: 'tech.henskens.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRxKxlyZN-HoZA5JIeh1gFOBUdc0qonwM',
    appId: '1:883212268237:ios:0dfc2a05c3e89cc864ef84',
    messagingSenderId: '883212268237',
    projectId: 'userservice-423506',
    storageBucket: 'userservice-423506.appspot.com',
    iosBundleId: 'tech.henskens.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVmEiJAaFOoibsIzX2JR-f90C12Jz09yY',
    appId: '1:883212268237:web:3e2e7021f4a0443d64ef84',
    messagingSenderId: '883212268237',
    projectId: 'userservice-423506',
    authDomain: 'userservice-423506.firebaseapp.com',
    storageBucket: 'userservice-423506.appspot.com',
    measurementId: 'G-MWJ6KT8X07',
  );
}
